Epic/lesson5/feature tests
nastylia/qna pull request #4
Opened 2017-02-23 23:03 UTC by nastylia

2017-02-24 06:36 UTC, vkurennov requested changes

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
У нас нет отдельной страницы со списком ответов, они выводятся на странице вопроса

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Экшена new тоже не должно быть, т.к. форма на странице вопроса и здесь ее и надо рендерить

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(@answer.question_id)
Зачем делать find, когда `@answer.question` сразу вернет нужный объект?

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy
У нас только автор может удалять, где эта проверка? На уровне вида мало, т.к. можно отправить запрос напрямую и удалить чужой ответ

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :author_id)
auhtor_id не приходит в форме (иначе, его легко подменить), мы его берем из current_user

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.destroy
Где проверка на автора?

2017-02-24 06:36 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :author_id)
author_id не приходит в параметрах формы

2017-02-24 06:36 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_for @question do |f|
Где вывод ошибок валидации?

2017-02-24 06:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user.id == @question.author_id
Проверка на автора верная, но она часто будет встречаться, и не только в видах, вынеси ее в метод `User#author_of?`  и используй этот метод

2017-02-24 06:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    - if user_signed_in? && current_user.id == a.author_id
Используй метод `User#author_of?`

2017-02-24 06:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_for [@question, @answer] do |f|
Где вывод ошибок валидации?

2017-02-24 06:36 UTC, vkurennov commented on db/migrate/20170222220136_add_user_id_to_questions.rb
> +    add_belongs_to :questions, :author
Добавляй опцию `foreign_key: true`, чтобы был контроль целостности данных на уровне БД

2017-02-24 06:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer, author_id: user.id), question_id: question } }.to change(Answer, :count).by(1)
author_id не передается в параметрах

2017-02-24 06:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer, author_id: user.id), question_id: question } }.to change(question.answers, :count).by(1)
author_id не передается в параметрах

2017-02-24 06:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Нужно проверить, что ответ связывается с залогиненным юзером

2017-02-24 06:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'delete #destroy' do
Тут должно быть 2 конеткста: для автора и для не-автора

2017-02-24 06:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question_author, author_id: user.id) } }.to change(Question, :count).by(1)
Надо проверить, что вопрос связывается с юзером и author_id не передается в параметрах

2017-02-24 06:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Нужно 2 контекста: для автора и для не автора

2017-02-24 06:36 UTC, vkurennov commented on spec/factories/questions.rb
> +  factory :questions, class: Question do
эта фабрика вообще не валидная, т.к. отсутствует обязательная ассоциация с юзером

2017-02-24 06:36 UTC, vkurennov commented on spec/feature/questions/author_delete_answer_spec.rb
> +  scenario 'Non-answer-author cannot delete someone else answer' do
Еще нужен похожий сценарий для незалогиненного юзера

2017-02-24 06:36 UTC, vkurennov commented on spec/feature/questions/author_delete_question_spec.rb
> +  scenario 'Non-question-author cannot delete others questions' do
Еще нужен похожий сценарий для незалогиненного юзера

2017-02-24 06:36 UTC, vkurennov commented on spec/feature/questions/create_answer_for_question_spec.rb
> +feature 'Create answer for a question', %q{
Нужен сценарий на невалидный ответ, все ошибки проверять не нужно, просто убедиться, что система их показывает юзеру

2017-02-24 06:36 UTC, vkurennov commented on spec/feature/questions/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий на невалидный вопрос

2017-02-24 13:36 UTC, nastylia commented on app/controllers/answers_controller.rb
>        render :new
@vkurennov, а в случае если наш ответ не валиден, то мы просто остаемся на той же странице @question? так? и отображаем сообщение о том что у нас не получилось сохранить ответ. Верно?

2017-02-26 09:02 UTC, vkurennov requested changes

2017-02-26 09:02 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      # render :"question/show"
Вот это было правильно, только символ там ни к чему,  render  умеет принимать символ, строку, объект, коллекцию и т.п. В общем, надо сделать так: `render 'quetions/show'` (и обрати внимание на множественное число questions, т.к. мы указываем путь к виду)

2017-02-26 09:02 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [:index, :show]
У тебя нет экшенов index и show

2017-02-26 09:02 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      else
Не используй else с unless, это усложняет понимание. Да и вообще, принято сначала "позитивный" сценарий описывать. Поменяй на if/else

2017-02-26 09:02 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if User.author_of? current_user, @question
Запись `User#author_of?` означает **инстанс-метод** (метод класса записывается через точку). Да и зачем вообще метод класса, когда у тебя есть конкретный юзер (current_user) и у него можно вызывать метод?

2017-02-26 09:02 UTC, vkurennov commented on app/models/user.rb
> +  def self.author_of?(user, item)
Почему это метод класса? Ведь мы работаем с конкретным объектом (инстансем), а значит, и надо делать инстанс-метод

2017-02-26 09:02 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  p= link_to "#{q.title}", question_path(q)
link_to принимает строку первым аргументом, q.title возвращает строку, зачем тут интерполяция?

2017-02-26 09:02 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    p #{a.body}
`p= a.body` Руби-вставки в slim реализуются через знаки равно или тире. Интерполяцию тоже можно использовать, но там, где и дет смешение html и ruby, как в 4-5 строках у тебя

2017-02-26 09:02 UTC, vkurennov commented on db/migrate/20170223220107_add_user_id_to_answers.rb
> +    add_belongs_to :answers, :author
А почему сразу не указать опцию `foriegn_key: true`

2017-02-26 09:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer in db' do
Тогда этот тест не нужен, двух следующих досаточно.

2017-02-26 09:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, id: answer }.to change(Answer, :count).by(0)
мы же не говорим "изменилось кол-во на ноль", мы говорим, "кол-во не изменилось" вот и пиши `to_not change(Answer, :count)`

2017-02-26 09:02 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, id: question }.to change(Question, :count).by(0)
`to_not change(...)`

2017-02-26 09:02 UTC, vkurennov commented on spec/feature/questions/author_delete_answer_spec.rb
> +    expect(page).to_not have_content answers_author1.body
Было бы правильно проверить, что этот контент есть на странице ДО удаления.

2017-02-26 09:02 UTC, vkurennov commented on spec/feature/questions/author_delete_question_spec.rb
> +    expect(page).to_not have_content question_author1.title
Было бы правильно проверить, что этот контент есть на странице ДО удаления.

2017-02-26 09:02 UTC, vkurennov commented on spec/feature/questions/create_answer_for_question_spec.rb
> +    save_and_open_page()
Зачем тут скобки? И удаляй эти вызовы, когда все готово

2017-02-26 09:02 UTC, vkurennov commented on spec/feature/questions/create_answer_for_question_spec.rb
> +    expect(page).to have_content 'Cannot save Answer:'
Этого не достаточно, надо проверить, что выводятся стандартные сообщения об ошибках валидации, а не то, сообщение, что в контроллере указано

2017-02-26 09:02 UTC, vkurennov commented on spec/feature/questions/create_question_spec.rb
> +    expect(page).to have_content 'Cannot save Question:'
И опять же нужно проверить сообщения о валидациях

2017-02-26 09:02 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
где тесты на метод author_of? (только на инстанс-метод его сначала исправь)

2017-02-26 09:19 UTC, nastylia commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [:index, :show]
упс, точно

2017-02-27 07:09 UTC, vkurennov approved these changes

2017-02-27 07:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.author_id = current_user.id
Присваиваем по объектам, это сравниваем по id, т.е. здесь достаточно `@answer.author = current_user`. С id рельсы сами разберутся

2017-02-27 07:09 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.author_id = current_user.id
Присваиваем по объектам

2017-02-27 07:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if user_signed_in? && current_user.author_of?(@answer)
Здесь нет смысла проверять на `user_signed_in?`, т.к. до экшена дойдет дело только если юзер залогинен (у тебя же стоит фильтр на authenticate_user). А вот в видах такакя проверка нужна.

2017-02-27 07:09 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if user_signed_in? && current_user.author_of?(@question)
`user_signed_in?` лишний

2017-02-27 07:09 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      end
Отделяй тесты друг от друга и от другого кода пустой строкой

2017-02-27 07:09 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it 'compares answer\'s author and user' do
У тебя же универсальный метод и будет работать с любым объетом, у которого есть метод `author_id`, поэтому не надо проверяеть его с каждым возможным вариантом, достаточно проверить только на вопросе или ответе.

2017-02-27 07:09 UTC, vkurennov commented on spec/models/user_spec.rb
> +    context 'item\'s author and user are different' do
Чтобы не использовать слеши перед апострофом используй двойный кавычки, а на ругательства рубокопа или RubyMine по этому поводу просто не обращай внимания.

2017-02-27 11:18 UTC, merged