Story/lesson6/ajax1
nastylia/qna pull request #5
Opened 2017-03-01 12:17 UTC by nastylia

2017-03-01 12:46 UTC, vkurennov requested changes

2017-03-01 12:46 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').append('<%= j render "questions/answer", answer: @answer %>')
Вспомни про анонимные паршалы и перенести паршл для ответа в answers/answer. Тогда можно один ответ будет рендерить так: `render @answer`, а коллекцию так: `render @question.answers`

2017-03-01 12:46 UTC, vkurennov commented on app/views/questions/_answer.html.slim
> +  - unless answer.id.nil?
Используй метод `persisted?` для определения, сохранен ли объект в базе. И проверку лучше вынести еще до блока .answer, к чему пустые блоки выводить на страницу?

2017-03-02 06:24 UTC, vkurennov approved these changes

2017-03-02 06:24 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'answers'
Раз у тебя есть паршл answers/_answer для одного ответа, то коллекцию можно отрендерить так: `render @question.answers`
Таким образом для каждого ответа в коллекции отрендерится паршл для одиночного ответа и паршл questions/_answers тебе уже не нужен будет

2017-03-02 10:27 UTC, nastylia commented on app/views/questions/show.html.slim
> +  = render 'answers'
Черт, точно!
Что-то я туплю :)

2017-03-02 10:27 UTC, merged